### ISSUE TITLE
Error: Cannot find module '../build/Debug/nodegit.node'

### ISSUE THREAD

**Issue by timkelty** [pswai/git-sweep#5]
On OSX, node 6.22 as well as 7.4.0.

```❯ git-sweep
module.js:472
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'```

**Comment by pswai** [comment]
@timkelty thanks for reporting! I'll have a look at it later today

**Comment by pswai** [comment]
Node 6.x and 7.x are not well-supported by the old version of 0.11.x.

Breaking:
With this upgrade Node 0.12.x support is dropped.
